### ISSUE TITLE
Issues with X12 code systems; Sample data improvements

### ISSUE THREAD

**Issue by maxim-gorshkov-isc** [inferno-framework/davinci-pas-test-kit#8]
My team and I have been utilizing Inferno's [PAS test kit](https://inferno-qa.healthit.gov/test-kits/davinci-pas) to validate our PAS response. There is a preset called “Prior Authorization Support Reference Implementation”, which comes with a sample PAS Request bundle, and we were hoping to ask you some questions about it.

1. Across multiple resource profiles, there seem to be inconsistencies with how the X12 value set URIs are formatted (with the same value set sometimes being referred to using two different URIs).
As an example: according to the FHIR IG, a [PAS Insurer Organization](https://build.fhir.org/ig/HL7/davinci-pas/StructureDefinition-profile-insurer.html) resource has a `type` field that uses codes from `https://valueset.x12.org/x217/005010/request/2010A/NM1/1/01/00/98`. However, in other places, we see codes from systems formatted like `https://codesystem.x12.org/005010/98`. Do you happen to know which one should be used? 
2. Is there any chance that your organization could provide some more variety of sample data that uses X12 value sets? Most codes being used in the sample bundle seem to come from HL7 value sets.
3. Besides that, it would also be great to see an example of a Claim where the Beneficiary Patient is a dependent of the insurance Subscriber.

Thank you!

Best,

Maxim Gorshkov and Jin Lou
HealthShare Data Transformations
[InterSystems](https://www.intersystems.com/)

**Comment by karlnaden** [comment]
Hi Maxim and Jin,

Thank you for using the Inferno PAS tests! In terms of examples, our team are not experts on X12 and the prior authorization workflow, so when we need additional examples, we go to the IG authors and PAS community either by attending the Da Vinci burden reduction calls (see Da Vinci's scheduled [here](https://confluence.hl7.org/pages/viewpage.action?pageId=40743189#DaVinciUseCases-WeeklyMeetingSchedule) - burden reduction is currently Wednesdays at 11am ET) or posting on the [burden reduction Zulip channel](https://chat.fhir.org/#narrow/stream/259713-Da-Vinci-Burden-Reduction-interoperability). If there are particular examples that you're interested in seeing, we'd recommend reaching out through one or both of those channels as they are the most likely to be able to help you.

In terms of your question on code systems vs value sets, at a high-level
- value sets are lists of codes from code systems which are used in profiles to indicate which codes are valid for a particular element
- code systems contain the definitions of codes and are used in instances to because they are part of a code's identity.

So, if you're seeing code systems in instances and value sets in profiles, then nothing is wrong. If you're seeing a value set indicated in the system element within an instance, then that's probably wrong (and the FHIR validator should say so).  I looked through our presets, canned response, and postman examples and didn't see any cases where a value set was present in an instance, but let us know if you are seeing one as we would want to fix it!

I'll also note that working with X12 codes and value sets is challenging because it is not an open standard. X12 does have membership options that provide access to these details, but If you're not in a place to purchase a membership to get access to X12 codes and value sets (we aren't), reaching out to the burden reduction community is probably your best bet.

Thanks again for using the tests and let us know if you have any other feedback,

The Inferno Team

**Comment by maxim-gorshkov-isc** [comment]
Thank you so much for the detailed reply! We will make sure to take advantage of the channels you recommended.
